// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urmylbivqqwclqtdlzzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVybXlsYml2cXF3Y2xxdGRsenpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDc4NTcsImV4cCI6MjA3Mjg4Mzg1N30.UXBGawws6r4hkBIAK13uxLrfvrWBxQJJMALyPWOagNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});